<footer class="footer syuanpi fadeIn" id="footer">
  <hr>
  <div class="footer-wrapper">
    <div class="left">
      {% include "_footer/contact.swig" %}
      <! --音乐-- >
      <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=298 height=52 src="//music.163.com/outchain/player?type=2&id=451543833&auto=0&height=32"></iframe>
    </div>
    <div class="right">
      {% include "_footer/copyright.swig" %}
    </div>
  </div>

</footer>